// This file is generated by Slice Machine. Update with care!

import EmailSignUp from './EmailSignUp';
import FrequentlyAskedQuestions from './FrequentlyAskedQuestions';
import Image from './Image';
import Marquee from './Marquee';
import Partners from './Partners';
import Schedule from './Schedule';
import Social from './Social';
import Text from './Text';
import TextAsset from './TextAsset';
import VideoPlayerEmbed from './VideoPlayerEmbed';

export {
	EmailSignUp,
	FrequentlyAskedQuestions,
	Image,
	Marquee,
	Partners,
	Schedule,
	Social,
	Text,
	TextAsset,
	VideoPlayerEmbed,
};

export const components = {
	email_sign_up: EmailSignUp,
	frequently_asked_questions: FrequentlyAskedQuestions,
	image: Image,
	marquee: Marquee,
	partners: Partners,
	schedule: Schedule,
	social: Social,
	text: Text,
	text_asset: TextAsset,
	video_player_embed: VideoPlayerEmbed,
};
