import Head from "next/head";
import styles from "@styles/Home.module.css";

export default function Home() {
  return (
    <>
      <Head>
        <title>Ones Basketball League</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>Ones Basketball League</h1>
      </main>
    </>
  );
}
